# Nombre de tu proyecto Angular
name = "Softevolucion"

# Versión de tu proyecto Angular
version = "1.0.0"

# Lista de paquetes Nix que deben estar disponibles para el proyecto
[nix_dependencies]
  angular-cli = "angular-cli"
  

[phases.build]
  cmds = ['npm run install --legacy-peer-deps ','npm run build']

[start]
  cmd = 'npm run dev'